 kitex -module douyin_rpc ../server/idl/comment.thrift
  kitex -module douyin_rpc ../server/idl/favorite.thrift
   kitex -module douyin_rpc ../server/idl/message.thrift
    kitex -module douyin_rpc ../server/idl/user.thrift
     kitex -module douyin_rpc ../server/idl/video.thrift
      kitex -module douyin_rpc ../server/idl/relation.thrift