global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['0.0.0.0:9090']
  - job_name: 'otel'
    static_configs:
      - targets: ['192.168.56.102:8888']