// Code generated by hertz generator.

package Api

import (
	"context"
	"douyin_rpc/server/cmd/api/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/limiter"
	"github.com/hertz-contrib/requestid"
	"go.opentelemetry.io/otel/trace"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		// use gzip mw
		gzip.Gzip(gzip.DefaultCompression, gzip.WithExcludedExtensions([]string{".jpg", ".mp4", ".png"})),
		// use limiter mw
		limiter.AdaptiveLimit(limiter.WithCPUThreshold(900)),
		// use requestId mw & bind with traceId
		requestid.New(
			requestid.WithGenerator(func(ctx context.Context, c *app.RequestContext) string {
				traceID := trace.SpanFromContext(ctx).SpanContext().TraceID().String()
				return traceID
			}),
		),
	}
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _comment_ctionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _listMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _commentlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _action0Mw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _favorite_ctionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoritelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feed0Mw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _action1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _message_ctionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _list1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messagelistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
	}
}

func _action2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publish_ctionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuthForm(),
	}
}

func _list2Mw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _publishlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _action3Mw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func __ctionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _followMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _list3Mw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _followlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _list4Mw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _followerlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _list5Mw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _friendlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.Recovery(),
		middleware.JWTAuth(),
	}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _login0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _register0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
