// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/douyin/comment/action/": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "评论操作，删除或增加",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "操作类型",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评论内容",
                        "name": "comment_text",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "评论id",
                        "name": "comment_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CommentActionResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.CommentActionResponse"
                        }
                    }
                }
            }
        },
        "/douyin/comment/list/": {
            "get": {
                "tags": [
                    "评论"
                ],
                "summary": "获取所有评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CommentListResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.CommentListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/favorite/action/": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "点赞"
                ],
                "summary": "点赞操作，点赞或取消点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "视频id",
                        "name": "video_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "事件类型，1点赞，2取消点赞",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CommentActionResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.CommentActionResponse"
                        }
                    }
                }
            }
        },
        "/douyin/favorite/list/": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "点赞"
                ],
                "summary": "获取所有点赞过的视频",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.FavoriteListResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.FavoriteListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/feed/": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "feed"
                ],
                "summary": "视频推流",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "latest_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.FeedResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.FeedResponse"
                        }
                    }
                }
            }
        },
        "/douyin/message/action/": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "发送消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "对方用户id",
                        "name": "to_user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "类型",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "消息内容",
                        "name": "content",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MessageActionResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.MessageActionResponse"
                        }
                    }
                }
            }
        },
        "/douyin/message/chat/": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "获取聊天记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "to_user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MessageListResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.MessageListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/message/list/": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "获取聊天记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "to_user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.MessageListResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.MessageListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/publish/action/": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "发布"
                ],
                "summary": "发布视频",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "视频",
                        "name": "data",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PublishActionResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.PublishActionResponse"
                        }
                    }
                }
            }
        },
        "/douyin/publish/list/": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "发布"
                ],
                "summary": "获取发布视频列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PublishListResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.PublishListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/relation/action/": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "关系"
                ],
                "summary": "关注和取消关注操作",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "to_user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "操作类型",
                        "name": "action_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RelationActionResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.RelationActionResponse"
                        }
                    }
                }
            }
        },
        "/douyin/relation/follow/list/": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "关系"
                ],
                "summary": "获取关注列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RelationFollowListResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.RelationFollowListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/relation/follower/list/": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "关系"
                ],
                "summary": "获取关注者列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RelationFollowerListResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.RelationFollowerListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/relation/friend/list/": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "关系"
                ],
                "summary": "获取好友列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RelationFriendListResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.RelationFriendListResponse"
                        }
                    }
                }
            }
        },
        "/douyin/user/": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.UserResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.UserResponse"
                        }
                    }
                }
            }
        },
        "/douyin/user/login/": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LoginResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.LoginResponse"
                        }
                    }
                }
            }
        },
        "/douyin/user/register/": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RegisterResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.RegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Code": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "Code_Success",
                "Code_ParamInvalid",
                "Code_DBError",
                "Code_ServerError"
            ]
        },
        "api.Comment": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "create_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/api.User"
                }
            }
        },
        "api.CommentActionResponse": {
            "type": "object",
            "properties": {
                "comment": {
                    "$ref": "#/definitions/api.Comment"
                },
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "api.CommentListResponse": {
            "type": "object",
            "properties": {
                "comment_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Comment"
                    }
                },
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "api.FavoriteListResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "video_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Video"
                    }
                }
            }
        },
        "api.FeedResponse": {
            "type": "object",
            "properties": {
                "next_time": {
                    "type": "integer"
                },
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "video_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Video"
                    }
                }
            }
        },
        "api.LoginResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "api.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "api.MessageActionResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "api.MessageListResponse": {
            "type": "object",
            "properties": {
                "message_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Message"
                    }
                },
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "api.PublishActionResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "api.PublishListResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "video_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Video"
                    }
                }
            }
        },
        "api.RegisterResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "api.RelationActionResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "api.RelationFollowListResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "user_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.User"
                    }
                }
            }
        },
        "api.RelationFollowerListResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "user_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.User"
                    }
                }
            }
        },
        "api.RelationFriendListResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "user_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.User"
                    }
                }
            }
        },
        "api.User": {
            "type": "object",
            "properties": {
                "follow_count": {
                    "type": "integer"
                },
                "follower_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_follow": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.UserResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/api.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/api.User"
                }
            }
        },
        "api.Video": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/api.User"
                },
                "comment_count": {
                    "type": "integer"
                },
                "cover_url": {
                    "type": "string"
                },
                "favorite_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_favorite": {
                    "type": "boolean"
                },
                "play_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
