basePath: /douyin
definitions:
  api.Code:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Code_Success
    - Code_ParamInvalid
    - Code_DBError
    - Code_ServerError
  api.RelationFollowListResponse:
    properties:
      status_code:
        $ref: '#/definitions/api.Code'
      status_msg:
        type: string
      user_list:
        items:
          $ref: '#/definitions/api.User'
        type: array
    type: object
  api.RelationFollowerListResponse:
    properties:
      status_code:
        $ref: '#/definitions/api.Code'
      status_msg:
        type: string
      user_list:
        items:
          $ref: '#/definitions/api.User'
        type: array
    type: object
  api.RelationFriendListResponse:
    properties:
      status_code:
        $ref: '#/definitions/api.Code'
      status_msg:
        type: string
      user_list:
        items:
          $ref: '#/definitions/api.User'
        type: array
    type: object
  api.User:
    properties:
      follow_count:
        type: integer
      follower_count:
        type: integer
      id:
        type: integer
      is_follow:
        type: boolean
      name:
        type: string
    type: object
  comment.Code:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Code_Success
    - Code_ParamInvalid
    - Code_DBError
    - Code_ServerError
  comment.Comment:
    properties:
      content:
        type: string
      create_date:
        type: string
      id:
        type: integer
      user:
        $ref: '#/definitions/comment.User'
    type: object
  comment.CommentActionResponse:
    properties:
      comment:
        $ref: '#/definitions/comment.Comment'
      status_code:
        $ref: '#/definitions/comment.Code'
      status_msg:
        type: string
    type: object
  comment.CommentListResponse:
    properties:
      comment_list:
        items:
          $ref: '#/definitions/comment.Comment'
        type: array
      status_code:
        $ref: '#/definitions/comment.Code'
      status_msg:
        type: string
    type: object
  comment.User:
    properties:
      follow_count:
        type: integer
      follower_count:
        type: integer
      id:
        type: integer
      is_follow:
        type: boolean
      name:
        type: string
    type: object
  favorite.Code:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Code_Success
    - Code_ParamInvalid
    - Code_DBError
    - Code_ServerError
  favorite.FavoriteActionRequest:
    properties:
      action_type:
        type: integer
      auth_id:
        type: integer
      video_id:
        type: integer
    type: object
  favorite.FavoriteListResponse:
    properties:
      status_code:
        $ref: '#/definitions/favorite.Code'
      status_msg:
        type: string
      video_list:
        items:
          $ref: '#/definitions/favorite.Video'
        type: array
    type: object
  favorite.User:
    properties:
      follow_count:
        type: integer
      follower_count:
        type: integer
      id:
        type: integer
      is_follow:
        type: boolean
      name:
        type: string
    type: object
  favorite.Video:
    properties:
      author:
        $ref: '#/definitions/favorite.User'
      comment_count:
        type: integer
      cover_url:
        type: string
      favorite_count:
        type: integer
      id:
        type: integer
      is_favorite:
        type: boolean
      play_url:
        type: string
      title:
        type: string
    type: object
  message.Code:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Code_Success
    - Code_ParamInvalid
    - Code_DBError
    - Code_ServerError
  message.Message:
    properties:
      content:
        type: string
      create_time:
        type: string
      id:
        type: integer
    type: object
  message.MessageActionResponse:
    properties:
      status_code:
        $ref: '#/definitions/message.Code'
      status_msg:
        type: string
    type: object
  message.MessageListResponse:
    properties:
      message_list:
        items:
          $ref: '#/definitions/message.Message'
        type: array
      status_code:
        $ref: '#/definitions/message.Code'
      status_msg:
        type: string
    type: object
  relation.Code:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Code_Success
    - Code_ParamInvalid
    - Code_DBError
    - Code_ServerError
  relation.RelationActionResponse:
    properties:
      status_code:
        $ref: '#/definitions/relation.Code'
      status_msg:
        type: string
    type: object
  user.Code:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Code_Success
    - Code_ParamInvalid
    - Code_DBError
    - Code_ServerError
  user.LoginResponse:
    properties:
      status_code:
        $ref: '#/definitions/user.Code'
      status_msg:
        type: string
      user_id:
        type: integer
    type: object
  user.RegisterResponse:
    properties:
      status_code:
        $ref: '#/definitions/user.Code'
      status_msg:
        type: string
      user_id:
        type: integer
    type: object
  user.User:
    properties:
      follow_count:
        type: integer
      follower_count:
        type: integer
      id:
        type: integer
      is_follow:
        type: boolean
      name:
        type: string
    type: object
  user.UserResponse:
    properties:
      status_code:
        $ref: '#/definitions/user.Code'
      status_msg:
        type: string
      user:
        $ref: '#/definitions/user.User'
    type: object
  video.Code:
    enum:
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - Code_Success
    - Code_ParamInvalid
    - Code_DBError
    - Code_ServerError
  video.FeedResponse:
    properties:
      next_time:
        type: integer
      status_code:
        $ref: '#/definitions/video.Code'
      status_msg:
        type: string
      video_list:
        items:
          $ref: '#/definitions/video.Video'
        type: array
    type: object
  video.PublishActionResponse:
    properties:
      status_code:
        $ref: '#/definitions/video.Code'
      status_msg:
        type: string
    type: object
  video.PublishListResponse:
    properties:
      status_code:
        $ref: '#/definitions/video.Code'
      status_msg:
        type: string
      video_list:
        items:
          $ref: '#/definitions/video.Video'
        type: array
    type: object
  video.User:
    properties:
      follow_count:
        type: integer
      follower_count:
        type: integer
      id:
        type: integer
      is_follow:
        type: boolean
      name:
        type: string
    type: object
  video.Video:
    properties:
      author:
        $ref: '#/definitions/video.User'
      comment_count:
        type: integer
      cover_url:
        type: string
      favorite_count:
        type: integer
      id:
        type: integer
      is_favorite:
        type: boolean
      play_url:
        type: string
      title:
        type: string
    type: object
host: 192.168.56.100:10000
info:
  contact:
    email: 1903317091@qq.com
    name: 余晓兵
    url: http://www.swagger.io/support
  description: 青训营抖音大项目
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: douyin
  version: "1.0"
paths:
  /douyin/comment/action/:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 操作类型
        in: query
        name: action_type
        required: true
        type: integer
      - description: 评论内容
        in: query
        name: comment_text
        type: string
      - description: 评论id
        in: query
        name: comment_id
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comment.CommentActionResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/comment.CommentActionResponse'
      summary: 评论操作，删除或增加
      tags:
      - 评论
  /douyin/comment/list/:
    get:
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comment.CommentListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/comment.CommentListResponse'
      summary: 获取所有评论
      tags:
      - 评论
  /douyin/favorite/action/:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: 事件类型，1点赞，2取消点赞
        in: query
        name: action_type
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/favorite.FavoriteActionRequest'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/favorite.FavoriteActionRequest'
      summary: 点赞操作，点赞或取消点赞
      tags:
      - 点赞
  /douyin/favorite/list/:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/favorite.FavoriteListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/favorite.FavoriteListResponse'
      summary: 获取所有点赞过的视频
      tags:
      - 点赞
  /douyin/feed/:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: latest_time
        type: integer
      - description: token
        in: query
        name: token
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video.FeedResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/video.FeedResponse'
      summary: 视频推流
      tags:
      - feed
  /douyin/message/action/:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 对方用户id
        in: query
        name: to_user_id
        required: true
        type: integer
      - description: 类型
        in: query
        name: action_type
        required: true
        type: integer
      - description: 消息内容
        in: query
        name: content
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.MessageActionResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/message.MessageActionResponse'
      summary: 发送消息
      tags:
      - 消息
  /douyin/message/chat/:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: to_user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.MessageListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/message.MessageListResponse'
      summary: 获取聊天记录
      tags:
      - 消息
  /douyin/message/list/:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: to_user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.MessageListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/message.MessageListResponse'
      summary: 获取聊天记录
      tags:
      - 消息
  /douyin/publish/action/:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: token
        in: formData
        name: token
        required: true
        type: string
      - description: 视频
        in: formData
        name: data
        required: true
        type: file
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video.PublishActionResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/video.PublishActionResponse'
      summary: 发布视频
      tags:
      - 发布
  /douyin/publish/list/:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video.PublishListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/video.PublishListResponse'
      summary: 获取发布视频列表
      tags:
      - 发布
  /douyin/relation/action/:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: to_user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 操作类型
        in: query
        name: action_type
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/relation.RelationActionResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/relation.RelationActionResponse'
      summary: 关注和取消关注操作
      tags:
      - 关系
  /douyin/relation/follow/list/:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.RelationFollowListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.RelationFollowListResponse'
      summary: 获取关注列表
      tags:
      - 关系
  /douyin/relation/follower/list/:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.RelationFollowerListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.RelationFollowerListResponse'
      summary: 获取关注者列表
      tags:
      - 关系
  /douyin/relation/friend/list/:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.RelationFriendListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.RelationFriendListResponse'
      summary: 获取好友列表
      tags:
      - 关系
  /douyin/user/:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/user.UserResponse'
      summary: 用户信息
      tags:
      - 用户
  /douyin/user/login/:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/user.LoginResponse'
      summary: 用户登录
      tags:
      - 用户
  /douyin/user/register/:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.RegisterResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/user.RegisterResponse'
      summary: 用户注册
      tags:
      - 用户
swagger: "2.0"
