// Code generated by hertz generator.

package main

import (
	"douyin_rpc/server/cmd/api/global"
	"douyin_rpc/server/cmd/api/initialize"
	"douyin_rpc/server/cmd/api/initialize/rpc"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/pprof"
)

func main() {
	initialize.InitLogger()
	r, info := initialize.InitNacos()
	//tracer, cfg := hertztracing.NewServerTracer()
	rpc.Init()
	h := server.New(
		//tracer,
		
		server.WithHostPorts(fmt.Sprintf(":%d", global.ServerConfig.Port)),
		server.WithRegistry(r, info),
		server.WithHandleMethodNotAllowed(true),
	)
	// use pprof & tracer mw
	pprof.Register(h)
	//h.Use(hertztracing.ServerMiddleware(cfg))
	register(h)
	h.Spin()
}
