 kitex -module douyin_rpc/server/cmd/api ../../idl/comment.thrift
  kitex -module douyin_rpc/server/cmd/api ../../idl/favorite.thrift
   kitex -module douyin_rpc/server/cmd/api ../../idl/message.thrift
    kitex -module douyin_rpc/server/cmd/api ../../idl/user.thrift
     kitex -module douyin_rpc/server/cmd/api ../../idl/video.thrift
      kitex -module douyin_rpc/server/cmd/api ../../idl/relation.thrift


      hz update --module douyin_rpc/server/cmd/api --idl ../../idl/api.thrift