// Code generated by hertz generator.

package api

import (
	"context"
	"douyin_rpc/server/cmd/api/global"
	"douyin_rpc/server/cmd/api/kitex_gen/video"
	"time"

	api "douyin_rpc/server/cmd/api/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Feed
// @Summary 视频推流
// @Tags feed
// @version 1.0
// @Accept application/x-json-stream
// @Param latest_time query int false "视频的最新时间"
// @Param token query string false "token"
// @Success 200 object video.FeedResponse 成功后返回值
// @Failure 409 object video.FeedResponse 失败后返回值
// @Router /douyin/feed/ [get]
// @router /douyin/feed/ [get]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	value, exist := c.Get("accountID")
	if !exist {
		value = int64(-1)
	}
	latest_time := int64(-1)
	parse, err1 := time.Parse("2006-01-02 15:04:05", req.LatestTime)
	if err1 == nil {
		latest_time = parse.Unix()
	}
	resp, err := global.VideoClient.Feed(ctx, &video.FeedRequest{
		AuthId:     value.(int64),
		LatestTime: latest_time,
	})
	if err != nil {
		resp.StatusCode = 4

		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusConflict, resp)
		return
	}
	//resp := new(api.FeedResponse)

	c.JSON(consts.StatusOK, resp)
}
