// Code generated by hertz generator.

package api

import (
	"context"
	"douyin_rpc/server/cmd/api/global"
	"douyin_rpc/server/cmd/api/kitex_gen/message"

	api "douyin_rpc/server/cmd/api/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// MessageAction
// @Summary 发送消息
// @Tags 消息
// @version 1.0
// @Accept application/x-json-stream
// @Param token query string true "token"
// @Param to_user_id query int true "对方用户id"
// @Param action_type query int true "类型"
// @Param content query string true "消息内容"
// @Success 200 object api.MessageActionResponse 成功后返回值
// @Failure 409 object api.MessageActionResponse 失败后返回值
// @Router /douyin/message/action/ [post]
// @router /douyin/message/action/ [POST]
func MessageAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MessageActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	value, exist := c.Get("accountID")
	if !exist {
		return
	}
	resp, err := global.MessageClient.MessageAction(ctx, &message.MessageActionRequest{
		ToUserId:   req.ToUserID,
		AuthId:     value.(int64),
		ActionType: req.ActionType,
		Content:    req.Content,
	})
	if err != nil {
		return
	}
	//resp := new(api.MessageActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// MessageList
// @Summary 获取聊天记录
// @Tags 消息
// @version 1.0
// @Accept application/x-json-stream
// @Param to_user_id query int true "用户id"
// @Param token query string true "token"
// @Success 200 object api.MessageListResponse 成功后返回值
// @Failure 409 object api.MessageListResponse 失败后返回值
// @Router /douyin/message/chat/ [get]
// @router /douyin/message/list/ [GET]
func MessageList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MessageListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	value, exist := c.Get("accountID")
	if !exist {
		return
	}
	resp, err := global.MessageClient.MessageList(ctx, &message.MessageListRequest{
		AuthId:   value.(int64),
		ToUserId: req.ToUserID,
	})
	if err != nil {
		return
	}
	//resp := new(api.MessageListResponse)

	c.JSON(consts.StatusOK, resp)
}
