cd comment && kitex -module douyin_rpc -service comment ../../idl/comment.thrift && cd ..
cd user && kitex -module douyin_rpc -service user ../../idl/user.thrift && cd ..
cd video && kitex -module douyin_rpc -service video ../../idl/video.thrift && cd ..
cd relation && kitex -module douyin_rpc -service relation ../../idl/relation.thrift && cd ..
cd message && kitex -module douyin_rpc -service message ../../idl/message.thrift && cd ..
cd favorite && kitex -module douyin_rpc -service favorite ../../idl/favorite.thrift && cd ..