basePath: /douyin
definitions:
  controllers.Comment:
    properties:
      content:
        type: string
      create_date:
        type: string
      id:
        type: integer
      user:
        $ref: '#/definitions/controllers.User'
    type: object
  controllers.CommentActionResponse:
    properties:
      comment:
        $ref: '#/definitions/controllers.Comment'
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  controllers.CommentListResponse:
    properties:
      comment_list:
        items:
          $ref: '#/definitions/controllers.Comment'
        type: array
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  controllers.FavoriteListResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      video_list:
        items:
          $ref: '#/definitions/controllers.Video'
        type: array
    type: object
  controllers.PostCommentActionForm:
    properties:
      action_type:
        type: integer
      comment_id:
        type: string
      comment_text:
        type: string
      token:
        type: string
      video_id:
        type: integer
    type: object
  controllers.PostFavoriteActionForm:
    properties:
      action_type:
        description: '1: 点赞，2:取消点赞'
        type: integer
      token:
        type: string
      video_id:
        type: integer
    type: object
  controllers.PostMessageActionForm:
    properties:
      action_type:
        type: integer
      content:
        type: string
      to_user_id:
        type: integer
      token:
        type: string
    type: object
  controllers.PostPublishActionForm:
    properties:
      content:
        type: string
      data:
        type: integer
      token:
        type: string
    type: object
  controllers.RelationList:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      user_list:
        items:
          $ref: '#/definitions/controllers.User'
        type: array
    type: object
  controllers.User:
    properties:
      follow_count:
        type: integer
      follower_count:
        type: integer
      is_follow:
        type: boolean
      user_id:
        type: integer
      user_name:
        type: string
    type: object
  controllers.UserInfoResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      user:
        $ref: '#/definitions/controllers.User'
    type: object
  controllers.Video:
    properties:
      comment_count:
        type: integer
      cover_url:
        type: string
      favorite_count:
        type: integer
      id:
        type: integer
      is_favorite:
        type: boolean
      play_url:
        type: string
      title:
        type: string
      user:
        $ref: '#/definitions/controllers.User'
    type: object
  utils.Response:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: 余晓兵
    url: http://www.swagger.io/support
  description: 青训营抖音大项目
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: douyin
  version: "1.0"
paths:
  /douyin/comment/action:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 文章
        in: body
        name: commentAction
        required: true
        schema:
          $ref: '#/definitions/controllers.PostCommentActionForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.CommentActionResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.CommentActionResponse'
      summary: 评论操作，删除或增加
      tags:
      - 评论
  /douyin/comment/list:
    get:
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.CommentListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.CommentListResponse'
      summary: 获取所有评论
      tags:
      - 评论
  /douyin/favorite/action:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 文章
        in: body
        name: favoriteAction
        required: true
        schema:
          $ref: '#/definitions/controllers.PostFavoriteActionForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.CommentActionResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.CommentActionResponse'
      summary: 点赞操作，点赞或取消点赞
      tags:
      - 点赞
  /douyin/favorite/list:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.FavoriteListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.FavoriteListResponse'
      summary: 获取所有点赞过的视频
      tags:
      - 点赞
  /douyin/feed:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: latest_time
        required: true
        type: integer
      - description: token
        in: query
        name: token
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.FavoriteListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.FavoriteListResponse'
      summary: 获取所有点赞过的视频
      tags:
      - feed
  /douyin/message/action:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 消息
        in: body
        name: messageAction
        required: true
        schema:
          $ref: '#/definitions/controllers.PostMessageActionForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 发送消息
      tags:
      - 消息
  /douyin/message/chat:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.FavoriteListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.FavoriteListResponse'
      summary: 获取聊天记录
      tags:
      - 消息
  /douyin/publish/action:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 视频信息
        in: body
        name: publishAction
        required: true
        schema:
          $ref: '#/definitions/controllers.PostPublishActionForm'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 获取聊天记录
      tags:
      - 发布
  /douyin/publish/list:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.FavoriteListResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.FavoriteListResponse'
      summary: 获取聊天记录
      tags:
      - 发布
  /douyin/relation/action:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: to_user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 操作类型
        in: query
        name: action_type
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 关注和取消关注操作
      tags:
      - 关系
  /douyin/relation/follow/list:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.RelationList'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.RelationList'
      summary: 获取关注列表
      tags:
      - 关系
  /douyin/relation/follower/list:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.RelationList'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.RelationList'
      summary: 获取关注者列表
      tags:
      - 关系
  /douyin/relation/friend/list:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.RelationList'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.RelationList'
      summary: 获取聊天记录
      tags:
      - 关系
  /douyin/user:
    get:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      - description: token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserInfoResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controllers.UserInfoResponse'
      summary: 用户信息
      tags:
      - 用户
  /douyin/user/login:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 用户登录
      tags:
      - 用户
  /douyin/user/register:
    post:
      consumes:
      - application/x-json-stream
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 用户注册
      tags:
      - 用户
swagger: "2.0"
